name: User Service CI

on:
  push:
    branches: [ "main" ]
    # 用户服务
    paths:
      - 'user_service/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push User Service
      uses: docker/build-push-action@v4
      with:
        context: ./user_service
        push: true
        tags: raitocc66/flash-user-service:latest